// ─── Country constants ────────────────────────────────────────────
// Used for phone number country selection and currency auto-selection.
// Covers ~195 countries with ISO-2 codes, dial codes, typical mobile
// digit lengths, and default currency codes.

export const DEFAULT_COUNTRY_CODE = "IN";

export interface CountryInfo {
  code: string;
  dialCode: string;
  name: string;
  flag: string;
  /** Typical mobile number digit count (without country code) */
  phoneLength: number;
  /** Default currency code for this country (used for auto-selection) */
  defaultCurrency: string;
}

// ─── Supported countries ──────────────────────────────────────────

export const COUNTRY_CODES: CountryInfo[] = [
  { code: "IN", dialCode: "+91", name: "India", flag: "🇮🇳", phoneLength: 10, defaultCurrency: "INR" },
  { code: "US", dialCode: "+1", name: "United States", flag: "🇺🇸", phoneLength: 10, defaultCurrency: "USD" },
  { code: "GB", dialCode: "+44", name: "United Kingdom", flag: "🇬🇧", phoneLength: 10, defaultCurrency: "GBP" },
  { code: "AE", dialCode: "+971", name: "United Arab Emirates", flag: "🇦🇪", phoneLength: 9, defaultCurrency: "AED" },
  { code: "SG", dialCode: "+65", name: "Singapore", flag: "🇸🇬", phoneLength: 8, defaultCurrency: "SGD" },
  { code: "AU", dialCode: "+61", name: "Australia", flag: "🇦🇺", phoneLength: 9, defaultCurrency: "AUD" },
  { code: "CA", dialCode: "+1", name: "Canada", flag: "🇨🇦", phoneLength: 10, defaultCurrency: "CAD" },
  { code: "JP", dialCode: "+81", name: "Japan", flag: "🇯🇵", phoneLength: 10, defaultCurrency: "JPY" },
  { code: "DE", dialCode: "+49", name: "Germany", flag: "🇩🇪", phoneLength: 10, defaultCurrency: "EUR" },
  { code: "FR", dialCode: "+33", name: "France", flag: "🇫🇷", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "SA", dialCode: "+966", name: "Saudi Arabia", flag: "🇸🇦", phoneLength: 9, defaultCurrency: "SAR" },
  { code: "PK", dialCode: "+92", name: "Pakistan", flag: "🇵🇰", phoneLength: 10, defaultCurrency: "PKR" },
  { code: "BD", dialCode: "+880", name: "Bangladesh", flag: "🇧🇩", phoneLength: 10, defaultCurrency: "BDT" },
  { code: "LK", dialCode: "+94", name: "Sri Lanka", flag: "🇱🇰", phoneLength: 10, defaultCurrency: "LKR" },
  { code: "NP", dialCode: "+977", name: "Nepal", flag: "🇳🇵", phoneLength: 10, defaultCurrency: "NPR" },
  { code: "ZA", dialCode: "+27", name: "South Africa", flag: "🇿🇦", phoneLength: 9, defaultCurrency: "ZAR" },
  { code: "NG", dialCode: "+234", name: "Nigeria", flag: "🇳🇬", phoneLength: 10, defaultCurrency: "NGN" },
  { code: "KE", dialCode: "+254", name: "Kenya", flag: "🇰🇪", phoneLength: 9, defaultCurrency: "KES" },
  { code: "IT", dialCode: "+39", name: "Italy", flag: "🇮🇹", phoneLength: 10, defaultCurrency: "EUR" },
  { code: "ES", dialCode: "+34", name: "Spain", flag: "🇪🇸", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "NL", dialCode: "+31", name: "Netherlands", flag: "🇳🇱", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "BE", dialCode: "+32", name: "Belgium", flag: "🇧🇪", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "AT", dialCode: "+43", name: "Austria", flag: "🇦🇹", phoneLength: 10, defaultCurrency: "EUR" },
  { code: "CH", dialCode: "+41", name: "Switzerland", flag: "🇨🇭", phoneLength: 9, defaultCurrency: "CHF" },
  { code: "SE", dialCode: "+46", name: "Sweden", flag: "🇸🇪", phoneLength: 9, defaultCurrency: "SEK" },
  { code: "NO", dialCode: "+47", name: "Norway", flag: "🇳🇴", phoneLength: 8, defaultCurrency: "NOK" },
  { code: "DK", dialCode: "+45", name: "Denmark", flag: "🇩🇰", phoneLength: 8, defaultCurrency: "DKK" },
  { code: "FI", dialCode: "+358", name: "Finland", flag: "🇫🇮", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "IE", dialCode: "+353", name: "Ireland", flag: "🇮🇪", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "PT", dialCode: "+351", name: "Portugal", flag: "🇵🇹", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "GR", dialCode: "+30", name: "Greece", flag: "🇬🇷", phoneLength: 10, defaultCurrency: "EUR" },
  { code: "PL", dialCode: "+48", name: "Poland", flag: "🇵🇱", phoneLength: 9, defaultCurrency: "PLN" },
  { code: "CZ", dialCode: "+420", name: "Czech Republic", flag: "🇨🇿", phoneLength: 9, defaultCurrency: "CZK" },
  { code: "HU", dialCode: "+36", name: "Hungary", flag: "🇭🇺", phoneLength: 9, defaultCurrency: "HUF" },
  { code: "RO", dialCode: "+40", name: "Romania", flag: "🇷🇴", phoneLength: 9, defaultCurrency: "RON" },
  { code: "BG", dialCode: "+359", name: "Bulgaria", flag: "🇧🇬", phoneLength: 9, defaultCurrency: "BGN" },
  { code: "HR", dialCode: "+385", name: "Croatia", flag: "🇭🇷", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "SK", dialCode: "+421", name: "Slovakia", flag: "🇸🇰", phoneLength: 9, defaultCurrency: "EUR" },
  { code: "SI", dialCode: "+386", name: "Slovenia", flag: "🇸🇮", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "LT", dialCode: "+370", name: "Lithuania", flag: "🇱🇹", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "LV", dialCode: "+371", name: "Latvia", flag: "🇱🇻", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "EE", dialCode: "+372", name: "Estonia", flag: "🇪🇪", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "IS", dialCode: "+354", name: "Iceland", flag: "🇮🇸", phoneLength: 7, defaultCurrency: "ISK" },
  { code: "LU", dialCode: "+352", name: "Luxembourg", flag: "🇱🇺", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "MT", dialCode: "+356", name: "Malta", flag: "🇲🇹", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "CY", dialCode: "+357", name: "Cyprus", flag: "🇨🇾", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "RU", dialCode: "+7", name: "Russia", flag: "🇷🇺", phoneLength: 10, defaultCurrency: "RUB" },
  { code: "UA", dialCode: "+380", name: "Ukraine", flag: "🇺🇦", phoneLength: 9, defaultCurrency: "UAH" },
  { code: "BY", dialCode: "+375", name: "Belarus", flag: "🇧🇾", phoneLength: 9, defaultCurrency: "BYN" },
  { code: "MD", dialCode: "+373", name: "Moldova", flag: "🇲🇩", phoneLength: 8, defaultCurrency: "MDL" },
  { code: "RS", dialCode: "+381", name: "Serbia", flag: "🇷🇸", phoneLength: 8, defaultCurrency: "RSD" },
  { code: "BA", dialCode: "+387", name: "Bosnia and Herzegovina", flag: "🇧🇦", phoneLength: 8, defaultCurrency: "BAM" },
  { code: "MK", dialCode: "+389", name: "North Macedonia", flag: "🇲🇰", phoneLength: 8, defaultCurrency: "MKD" },
  { code: "AL", dialCode: "+355", name: "Albania", flag: "🇦🇱", phoneLength: 9, defaultCurrency: "ALL" },
  { code: "ME", dialCode: "+382", name: "Montenegro", flag: "🇲🇪", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "XK", dialCode: "+383", name: "Kosovo", flag: "🇽🇰", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "CN", dialCode: "+86", name: "China", flag: "🇨🇳", phoneLength: 11, defaultCurrency: "CNY" },
  { code: "HK", dialCode: "+852", name: "Hong Kong", flag: "🇭🇰", phoneLength: 8, defaultCurrency: "HKD" },
  { code: "TW", dialCode: "+886", name: "Taiwan", flag: "🇹🇼", phoneLength: 9, defaultCurrency: "TWD" },
  { code: "KR", dialCode: "+82", name: "South Korea", flag: "🇰🇷", phoneLength: 10, defaultCurrency: "KRW" },
  { code: "KP", dialCode: "+850", name: "North Korea", flag: "🇰🇵", phoneLength: 10, defaultCurrency: "KPW" },
  { code: "TH", dialCode: "+66", name: "Thailand", flag: "🇹🇭", phoneLength: 9, defaultCurrency: "THB" },
  { code: "VN", dialCode: "+84", name: "Vietnam", flag: "🇻🇳", phoneLength: 9, defaultCurrency: "VND" },
  { code: "MY", dialCode: "+60", name: "Malaysia", flag: "🇲🇾", phoneLength: 9, defaultCurrency: "MYR" },
  { code: "ID", dialCode: "+62", name: "Indonesia", flag: "🇮🇩", phoneLength: 10, defaultCurrency: "IDR" },
  { code: "PH", dialCode: "+63", name: "Philippines", flag: "🇵🇭", phoneLength: 10, defaultCurrency: "PHP" },
  { code: "BN", dialCode: "+673", name: "Brunei", flag: "🇧🇳", phoneLength: 7, defaultCurrency: "BND" },
  { code: "KH", dialCode: "+855", name: "Cambodia", flag: "🇰🇭", phoneLength: 9, defaultCurrency: "KHR" },
  { code: "LA", dialCode: "+856", name: "Laos", flag: "🇱🇦", phoneLength: 9, defaultCurrency: "LAK" },
  { code: "MM", dialCode: "+95", name: "Myanmar", flag: "🇲🇲", phoneLength: 9, defaultCurrency: "MMK" },
  { code: "TL", dialCode: "+670", name: "Timor-Leste", flag: "🇹🇱", phoneLength: 8, defaultCurrency: "USD" },
  { code: "MO", dialCode: "+853", name: "Macao", flag: "🇲🇴", phoneLength: 8, defaultCurrency: "MOP" },
  { code: "AF", dialCode: "+93", name: "Afghanistan", flag: "🇦🇫", phoneLength: 9, defaultCurrency: "AFN" },
  { code: "IR", dialCode: "+98", name: "Iran", flag: "🇮🇷", phoneLength: 10, defaultCurrency: "IRR" },
  { code: "IQ", dialCode: "+964", name: "Iraq", flag: "🇮🇶", phoneLength: 10, defaultCurrency: "IQD" },
  { code: "SY", dialCode: "+963", name: "Syria", flag: "🇸🇾", phoneLength: 9, defaultCurrency: "SYP" },
  { code: "LB", dialCode: "+961", name: "Lebanon", flag: "🇱🇧", phoneLength: 8, defaultCurrency: "LBP" },
  { code: "JO", dialCode: "+962", name: "Jordan", flag: "🇯🇴", phoneLength: 9, defaultCurrency: "JOD" },
  { code: "IL", dialCode: "+972", name: "Israel", flag: "🇮🇱", phoneLength: 9, defaultCurrency: "ILS" },
  { code: "PS", dialCode: "+970", name: "Palestine", flag: "🇵🇸", phoneLength: 9, defaultCurrency: "ILS" },
  { code: "YE", dialCode: "+967", name: "Yemen", flag: "🇾🇪", phoneLength: 9, defaultCurrency: "YER" },
  { code: "OM", dialCode: "+968", name: "Oman", flag: "🇴🇲", phoneLength: 8, defaultCurrency: "OMR" },
  { code: "QA", dialCode: "+974", name: "Qatar", flag: "🇶🇦", phoneLength: 8, defaultCurrency: "QAR" },
  { code: "KW", dialCode: "+965", name: "Kuwait", flag: "🇰🇼", phoneLength: 8, defaultCurrency: "KWD" },
  { code: "BH", dialCode: "+973", name: "Bahrain", flag: "🇧🇭", phoneLength: 8, defaultCurrency: "BHD" },
  { code: "TR", dialCode: "+90", name: "Turkey", flag: "🇹🇷", phoneLength: 10, defaultCurrency: "TRY" },
  { code: "EG", dialCode: "+20", name: "Egypt", flag: "🇪🇬", phoneLength: 10, defaultCurrency: "EGP" },
  { code: "LY", dialCode: "+218", name: "Libya", flag: "🇱🇾", phoneLength: 9, defaultCurrency: "LYD" },
  { code: "TN", dialCode: "+216", name: "Tunisia", flag: "🇹🇳", phoneLength: 8, defaultCurrency: "TND" },
  { code: "DZ", dialCode: "+213", name: "Algeria", flag: "🇩🇿", phoneLength: 9, defaultCurrency: "DZD" },
  { code: "MA", dialCode: "+212", name: "Morocco", flag: "🇲🇦", phoneLength: 9, defaultCurrency: "MAD" },
  { code: "SD", dialCode: "+249", name: "Sudan", flag: "🇸🇩", phoneLength: 9, defaultCurrency: "SDG" },
  { code: "SS", dialCode: "+211", name: "South Sudan", flag: "🇸🇸", phoneLength: 9, defaultCurrency: "SSP" },
  { code: "ET", dialCode: "+251", name: "Ethiopia", flag: "🇪🇹", phoneLength: 9, defaultCurrency: "ETB" },
  { code: "ER", dialCode: "+291", name: "Eritrea", flag: "🇪🇷", phoneLength: 7, defaultCurrency: "ERN" },
  { code: "DJ", dialCode: "+253", name: "Djibouti", flag: "🇩🇯", phoneLength: 8, defaultCurrency: "DJF" },
  { code: "SO", dialCode: "+252", name: "Somalia", flag: "🇸🇴", phoneLength: 9, defaultCurrency: "SOS" },
  { code: "TZ", dialCode: "+255", name: "Tanzania", flag: "🇹🇿", phoneLength: 9, defaultCurrency: "TZS" },
  { code: "UG", dialCode: "+256", name: "Uganda", flag: "🇺🇬", phoneLength: 9, defaultCurrency: "UGX" },
  { code: "RW", dialCode: "+250", name: "Rwanda", flag: "🇷🇼", phoneLength: 9, defaultCurrency: "RWF" },
  { code: "BI", dialCode: "+257", name: "Burundi", flag: "🇧🇮", phoneLength: 8, defaultCurrency: "BIF" },
  { code: "MZ", dialCode: "+258", name: "Mozambique", flag: "🇲🇿", phoneLength: 9, defaultCurrency: "MZN" },
  { code: "ZW", dialCode: "+263", name: "Zimbabwe", flag: "🇿🇼", phoneLength: 9, defaultCurrency: "ZWL" },
  { code: "ZM", dialCode: "+260", name: "Zambia", flag: "🇿🇲", phoneLength: 9, defaultCurrency: "ZMW" },
  { code: "MW", dialCode: "+265", name: "Malawi", flag: "🇲🇼", phoneLength: 9, defaultCurrency: "MWK" },
  { code: "BW", dialCode: "+267", name: "Botswana", flag: "🇧🇼", phoneLength: 8, defaultCurrency: "BWP" },
  { code: "NA", dialCode: "+264", name: "Namibia", flag: "🇳🇦", phoneLength: 9, defaultCurrency: "NAD" },
  { code: "LS", dialCode: "+266", name: "Lesotho", flag: "🇱🇸", phoneLength: 8, defaultCurrency: "LSL" },
  { code: "SZ", dialCode: "+268", name: "Eswatini", flag: "🇸🇿", phoneLength: 8, defaultCurrency: "SZL" },
  { code: "AO", dialCode: "+244", name: "Angola", flag: "🇦🇴", phoneLength: 9, defaultCurrency: "AOA" },
  { code: "GH", dialCode: "+233", name: "Ghana", flag: "🇬🇭", phoneLength: 9, defaultCurrency: "GHS" },
  { code: "CI", dialCode: "+225", name: "Côte d'Ivoire", flag: "🇨🇮", phoneLength: 10, defaultCurrency: "XOF" },
  { code: "SN", dialCode: "+221", name: "Senegal", flag: "🇸🇳", phoneLength: 9, defaultCurrency: "XOF" },
  { code: "ML", dialCode: "+223", name: "Mali", flag: "🇲🇱", phoneLength: 8, defaultCurrency: "XOF" },
  { code: "BF", dialCode: "+226", name: "Burkina Faso", flag: "🇧🇫", phoneLength: 8, defaultCurrency: "XOF" },
  { code: "NE", dialCode: "+227", name: "Niger", flag: "🇳🇪", phoneLength: 8, defaultCurrency: "XOF" },
  { code: "BJ", dialCode: "+229", name: "Benin", flag: "🇧🇯", phoneLength: 8, defaultCurrency: "XOF" },
  { code: "TG", dialCode: "+228", name: "Togo", flag: "🇹🇬", phoneLength: 8, defaultCurrency: "XOF" },
  { code: "GN", dialCode: "+224", name: "Guinea", flag: "🇬🇳", phoneLength: 9, defaultCurrency: "GNF" },
  { code: "SL", dialCode: "+232", name: "Sierra Leone", flag: "🇸🇱", phoneLength: 8, defaultCurrency: "SLL" },
  { code: "LR", dialCode: "+231", name: "Liberia", flag: "🇱🇷", phoneLength: 9, defaultCurrency: "LRD" },
  { code: "MR", dialCode: "+222", name: "Mauritania", flag: "🇲🇷", phoneLength: 8, defaultCurrency: "MRU" },
  { code: "GM", dialCode: "+220", name: "Gambia", flag: "🇬🇲", phoneLength: 7, defaultCurrency: "GMD" },
  { code: "CV", dialCode: "+238", name: "Cape Verde", flag: "🇨🇻", phoneLength: 7, defaultCurrency: "CVE" },
  { code: "ST", dialCode: "+239", name: "São Tomé and Príncipe", flag: "🇸🇹", phoneLength: 7, defaultCurrency: "STN" },
  { code: "GW", dialCode: "+245", name: "Guinea-Bissau", flag: "🇬🇼", phoneLength: 9, defaultCurrency: "XOF" },
  { code: "GQ", dialCode: "+240", name: "Equatorial Guinea", flag: "🇬🇶", phoneLength: 9, defaultCurrency: "XAF" },
  { code: "GA", dialCode: "+241", name: "Gabon", flag: "🇬🇦", phoneLength: 8, defaultCurrency: "XAF" },
  { code: "CG", dialCode: "+242", name: "Congo", flag: "🇨🇬", phoneLength: 9, defaultCurrency: "XAF" },
  { code: "CD", dialCode: "+243", name: "DR Congo", flag: "🇨🇩", phoneLength: 9, defaultCurrency: "CDF" },
  { code: "TD", dialCode: "+235", name: "Chad", flag: "🇹🇩", phoneLength: 8, defaultCurrency: "XAF" },
  { code: "CF", dialCode: "+236", name: "Central African Republic", flag: "🇨🇫", phoneLength: 8, defaultCurrency: "XAF" },
  { code: "CM", dialCode: "+237", name: "Cameroon", flag: "🇨🇲", phoneLength: 9, defaultCurrency: "XAF" },
  { code: "KM", dialCode: "+269", name: "Comoros", flag: "🇰🇲", phoneLength: 7, defaultCurrency: "KMF" },
  { code: "MG", dialCode: "+261", name: "Madagascar", flag: "🇲🇬", phoneLength: 9, defaultCurrency: "MGA" },
  { code: "MU", dialCode: "+230", name: "Mauritius", flag: "🇲🇺", phoneLength: 8, defaultCurrency: "MUR" },
  { code: "SC", dialCode: "+248", name: "Seychelles", flag: "🇸🇨", phoneLength: 7, defaultCurrency: "SCR" },
  { code: "BR", dialCode: "+55", name: "Brazil", flag: "🇧🇷", phoneLength: 11, defaultCurrency: "BRL" },
  { code: "AR", dialCode: "+54", name: "Argentina", flag: "🇦🇷", phoneLength: 10, defaultCurrency: "ARS" },
  { code: "MX", dialCode: "+52", name: "Mexico", flag: "🇲🇽", phoneLength: 10, defaultCurrency: "MXN" },
  { code: "CO", dialCode: "+57", name: "Colombia", flag: "🇨🇴", phoneLength: 10, defaultCurrency: "COP" },
  { code: "CL", dialCode: "+56", name: "Chile", flag: "🇨🇱", phoneLength: 9, defaultCurrency: "CLP" },
  { code: "PE", dialCode: "+51", name: "Peru", flag: "🇵🇪", phoneLength: 9, defaultCurrency: "PEN" },
  { code: "VE", dialCode: "+58", name: "Venezuela", flag: "🇻🇪", phoneLength: 10, defaultCurrency: "VES" },
  { code: "EC", dialCode: "+593", name: "Ecuador", flag: "🇪🇨", phoneLength: 9, defaultCurrency: "USD" },
  { code: "BO", dialCode: "+591", name: "Bolivia", flag: "🇧🇴", phoneLength: 8, defaultCurrency: "BOB" },
  { code: "PY", dialCode: "+595", name: "Paraguay", flag: "🇵🇾", phoneLength: 9, defaultCurrency: "PYG" },
  { code: "UY", dialCode: "+598", name: "Uruguay", flag: "🇺🇾", phoneLength: 8, defaultCurrency: "UYU" },
  { code: "GY", dialCode: "+592", name: "Guyana", flag: "🇬🇾", phoneLength: 7, defaultCurrency: "GYD" },
  { code: "SR", dialCode: "+597", name: "Suriname", flag: "🇸🇷", phoneLength: 7, defaultCurrency: "SRD" },
  { code: "CR", dialCode: "+506", name: "Costa Rica", flag: "🇨🇷", phoneLength: 8, defaultCurrency: "CRC" },
  { code: "PA", dialCode: "+507", name: "Panama", flag: "🇵🇦", phoneLength: 8, defaultCurrency: "USD" },
  { code: "GT", dialCode: "+502", name: "Guatemala", flag: "🇬🇹", phoneLength: 8, defaultCurrency: "GTQ" },
  { code: "HN", dialCode: "+504", name: "Honduras", flag: "🇭🇳", phoneLength: 8, defaultCurrency: "HNL" },
  { code: "SV", dialCode: "+503", name: "El Salvador", flag: "🇸🇻", phoneLength: 8, defaultCurrency: "USD" },
  { code: "NI", dialCode: "+505", name: "Nicaragua", flag: "🇳🇮", phoneLength: 8, defaultCurrency: "NIO" },
  { code: "CU", dialCode: "+53", name: "Cuba", flag: "🇨🇺", phoneLength: 8, defaultCurrency: "CUP" },
  { code: "DO", dialCode: "+1", name: "Dominican Republic", flag: "🇩🇴", phoneLength: 10, defaultCurrency: "DOP" },
  { code: "HT", dialCode: "+509", name: "Haiti", flag: "🇭🇹", phoneLength: 8, defaultCurrency: "HTG" },
  { code: "JM", dialCode: "+1", name: "Jamaica", flag: "🇯🇲", phoneLength: 10, defaultCurrency: "JMD" },
  { code: "TT", dialCode: "+1", name: "Trinidad and Tobago", flag: "🇹🇹", phoneLength: 10, defaultCurrency: "TTD" },
  { code: "BB", dialCode: "+1", name: "Barbados", flag: "🇧🇧", phoneLength: 10, defaultCurrency: "BBD" },
  { code: "BS", dialCode: "+1", name: "Bahamas", flag: "🇧🇸", phoneLength: 10, defaultCurrency: "BSD" },
  { code: "GD", dialCode: "+1", name: "Grenada", flag: "🇬🇩", phoneLength: 10, defaultCurrency: "XCD" },
  { code: "LC", dialCode: "+1", name: "Saint Lucia", flag: "🇱🇨", phoneLength: 10, defaultCurrency: "XCD" },
  { code: "VC", dialCode: "+1", name: "Saint Vincent", flag: "🇻🇨", phoneLength: 10, defaultCurrency: "XCD" },
  { code: "AG", dialCode: "+1", name: "Antigua and Barbuda", flag: "🇦🇬", phoneLength: 10, defaultCurrency: "XCD" },
  { code: "DM", dialCode: "+1", name: "Dominica", flag: "🇩🇲", phoneLength: 10, defaultCurrency: "XCD" },
  { code: "KN", dialCode: "+1", name: "Saint Kitts and Nevis", flag: "🇰🇳", phoneLength: 10, defaultCurrency: "XCD" },
  { code: "BZ", dialCode: "+501", name: "Belize", flag: "🇧🇿", phoneLength: 7, defaultCurrency: "BZD" },
  { code: "PR", dialCode: "+1", name: "Puerto Rico", flag: "🇵🇷", phoneLength: 10, defaultCurrency: "USD" },
  { code: "NZ", dialCode: "+64", name: "New Zealand", flag: "🇳🇿", phoneLength: 9, defaultCurrency: "NZD" },
  { code: "FJ", dialCode: "+679", name: "Fiji", flag: "🇫🇯", phoneLength: 7, defaultCurrency: "FJD" },
  { code: "PG", dialCode: "+675", name: "Papua New Guinea", flag: "🇵🇬", phoneLength: 8, defaultCurrency: "PGK" },
  { code: "SB", dialCode: "+677", name: "Solomon Islands", flag: "🇸🇧", phoneLength: 7, defaultCurrency: "SBD" },
  { code: "VU", dialCode: "+678", name: "Vanuatu", flag: "🇻🇺", phoneLength: 7, defaultCurrency: "VUV" },
  { code: "WS", dialCode: "+685", name: "Samoa", flag: "🇼🇸", phoneLength: 7, defaultCurrency: "WST" },
  { code: "TO", dialCode: "+676", name: "Tonga", flag: "🇹🇴", phoneLength: 7, defaultCurrency: "TOP" },
  { code: "KI", dialCode: "+686", name: "Kiribati", flag: "🇰🇮", phoneLength: 5, defaultCurrency: "AUD" },
  { code: "TV", dialCode: "+688", name: "Tuvalu", flag: "🇹🇻", phoneLength: 5, defaultCurrency: "AUD" },
  { code: "NR", dialCode: "+674", name: "Nauru", flag: "🇳🇷", phoneLength: 7, defaultCurrency: "AUD" },
  { code: "PW", dialCode: "+680", name: "Palau", flag: "🇵🇼", phoneLength: 7, defaultCurrency: "USD" },
  { code: "MH", dialCode: "+692", name: "Marshall Islands", flag: "🇲🇭", phoneLength: 7, defaultCurrency: "USD" },
  { code: "FM", dialCode: "+691", name: "Micronesia", flag: "🇫🇲", phoneLength: 7, defaultCurrency: "USD" },
  { code: "CK", dialCode: "+682", name: "Cook Islands", flag: "🇨🇰", phoneLength: 5, defaultCurrency: "NZD" },
  { code: "NU", dialCode: "+683", name: "Niue", flag: "🇳🇺", phoneLength: 4, defaultCurrency: "NZD" },
  { code: "KZ", dialCode: "+7", name: "Kazakhstan", flag: "🇰🇿", phoneLength: 10, defaultCurrency: "KZT" },
  { code: "UZ", dialCode: "+998", name: "Uzbekistan", flag: "🇺🇿", phoneLength: 9, defaultCurrency: "UZS" },
  { code: "TM", dialCode: "+993", name: "Turkmenistan", flag: "🇹🇲", phoneLength: 8, defaultCurrency: "TMT" },
  { code: "KG", dialCode: "+996", name: "Kyrgyzstan", flag: "🇰🇬", phoneLength: 9, defaultCurrency: "KGS" },
  { code: "TJ", dialCode: "+992", name: "Tajikistan", flag: "🇹🇯", phoneLength: 9, defaultCurrency: "TJS" },
  { code: "MN", dialCode: "+976", name: "Mongolia", flag: "🇲🇳", phoneLength: 8, defaultCurrency: "MNT" },
  { code: "GE", dialCode: "+995", name: "Georgia", flag: "🇬🇪", phoneLength: 9, defaultCurrency: "GEL" },
  { code: "AM", dialCode: "+374", name: "Armenia", flag: "🇦🇲", phoneLength: 9, defaultCurrency: "AMD" },
  { code: "AZ", dialCode: "+994", name: "Azerbaijan", flag: "🇦🇿", phoneLength: 9, defaultCurrency: "AZN" },
  { code: "BT", dialCode: "+975", name: "Bhutan", flag: "🇧🇹", phoneLength: 8, defaultCurrency: "BTN" },
  { code: "MV", dialCode: "+960", name: "Maldives", flag: "🇲🇻", phoneLength: 7, defaultCurrency: "MVR" },
  { code: "VA", dialCode: "+39", name: "Vatican City", flag: "🇻🇦", phoneLength: 10, defaultCurrency: "EUR" },
  { code: "MC", dialCode: "+377", name: "Monaco", flag: "🇲🇨", phoneLength: 8, defaultCurrency: "EUR" },
  { code: "SM", dialCode: "+378", name: "San Marino", flag: "🇸🇲", phoneLength: 10, defaultCurrency: "EUR" },
  { code: "AD", dialCode: "+376", name: "Andorra", flag: "🇦🇩", phoneLength: 6, defaultCurrency: "EUR" },
  { code: "LI", dialCode: "+423", name: "Liechtenstein", flag: "🇱🇮", phoneLength: 7, defaultCurrency: "CHF" },
];

/** Set of all supported country codes for validation */
export const SUPPORTED_COUNTRY_CODES = new Set(COUNTRY_CODES.map((c) => c.code));

/** Check if a country code is supported */
export function isSupportedCountry(code: string): boolean {
  return SUPPORTED_COUNTRY_CODES.has(code);
}

/** Look up a country by its ISO-2 code; falls back to the default country */
export function getCountryByCode(code: string): CountryInfo {
  return COUNTRY_CODES.find((c) => c.code === code) || COUNTRY_CODES[0];
}

/** Get the default currency for a given country code */
export function getCurrencyForCountry(countryCode: string): string {
  return getCountryByCode(countryCode).defaultCurrency;
}
