// ─── Currency constants ───────────────────────────────────────────
// All monetary amounts are stored in the base currency in Firestore.
// Per-user display conversion happens at render time via exchange rates.

export const BASE_CURRENCY = "INR";

/** Default currency for new users who haven't set one yet */
export const DEFAULT_CURRENCY = "INR";

// ─── Currency → locale mapping (for number/date formatting) ───────

export const CURRENCY_LOCALE_MAP: Record<string, string> = {
  INR: "en-IN",
  USD: "en-US",
  EUR: "en-IE",
  GBP: "en-GB",
  JPY: "ja-JP",
  AUD: "en-AU",
  CAD: "en-CA",
  SGD: "en-SG",
  AED: "ar-AE",
  SAR: "ar-SA",
  PKR: "ur-PK",
  BDT: "bn-BD",
  LKR: "en-LK",
  NPR: "ne-NP",
  ZAR: "en-ZA",
  NGN: "en-NG",
  KES: "sw-KE",
  CHF: "de-CH",
  SEK: "sv-SE",
  NOK: "nb-NO",
  DKK: "da-DK",
  PLN: "pl-PL",
  CZK: "cs-CZ",
  HUF: "hu-HU",
  RON: "ro-RO",
  BGN: "bg-BG",
  HRK: "hr-HR",
  ISK: "is-IS",
  RUB: "ru-RU",
  UAH: "uk-UA",
  BYN: "be-BY",
  MDL: "ro-MD",
  RSD: "sr-RS",
  BAM: "bs-BA",
  MKD: "mk-MK",
  ALL: "sq-AL",
  CNY: "zh-CN",
  HKD: "zh-HK",
  TWD: "zh-TW",
  KRW: "ko-KR",
  KPW: "ko-KP",
  THB: "th-TH",
  VND: "vi-VN",
  MYR: "ms-MY",
  IDR: "id-ID",
  PHP: "en-PH",
  BND: "ms-BN",
  KHR: "km-KH",
  LAK: "lo-LA",
  MMK: "my-MM",
  MOP: "zh-MO",
  AFN: "fa-AF",
  IRR: "fa-IR",
  IQD: "ar-IQ",
  SYP: "ar-SY",
  LBP: "ar-LB",
  JOD: "ar-JO",
  ILS: "he-IL",
  YER: "ar-YE",
  OMR: "ar-OM",
  QAR: "ar-QA",
  KWD: "ar-KW",
  BHD: "ar-BH",
  TRY: "tr-TR",
  EGP: "ar-EG",
  LYD: "ar-LY",
  TND: "ar-TN",
  DZD: "ar-DZ",
  MAD: "ar-MA",
  SDG: "ar-SD",
  SSP: "ar-SS",
  ETB: "am-ET",
  ERN: "ti-ER",
  DJF: "fr-DJ",
  SOS: "so-SO",
  TZS: "sw-TZ",
  UGX: "sw-UG",
  RWF: "rw-RW",
  BIF: "fr-BI",
  MZN: "pt-MZ",
  ZWL: "en-ZW",
  ZMW: "en-ZM",
  MWK: "ny-MW",
  BWP: "en-BW",
  NAD: "en-NA",
  LSL: "en-LS",
  SZL: "en-SZ",
  AOA: "pt-AO",
  GHS: "ak-GH",
  XOF: "fr-SN",
  GNF: "fr-GN",
  SLL: "en-SL",
  LRD: "en-LR",
  MRU: "ar-MR",
  GMD: "en-GM",
  CVE: "pt-CV",
  STN: "pt-ST",
  XAF: "fr-CM",
  CDF: "fr-CD",
  KMF: "ar-KM",
  MGA: "mg-MG",
  MUR: "en-MU",
  SCR: "en-SC",
  BRL: "pt-BR",
  ARS: "es-AR",
  MXN: "es-MX",
  COP: "es-CO",
  CLP: "es-CL",
  PEN: "es-PE",
  VES: "es-VE",
  BOB: "es-BO",
  PYG: "es-PY",
  UYU: "es-UY",
  GYD: "en-GY",
  SRD: "nl-SR",
  CRC: "es-CR",
  GTQ: "es-GT",
  HNL: "es-HN",
  NIO: "es-NI",
  CUP: "es-CU",
  DOP: "es-DO",
  HTG: "ht-HT",
  JMD: "en-JM",
  TTD: "en-TT",
  BBD: "en-BB",
  BSD: "en-BS",
  XCD: "en-GD",
  BZD: "en-BZ",
  NZD: "en-NZ",
  FJD: "en-FJ",
  PGK: "en-PG",
  SBD: "en-SB",
  VUV: "bi-VU",
  WST: "en-WS",
  TOP: "en-TO",
  KZT: "kk-KZ",
  UZS: "uz-UZ",
  TMT: "tk-TM",
  KGS: "ky-KG",
  TJS: "tg-TJ",
  MNT: "mn-MN",
  GEL: "ka-GE",
  AMD: "hy-AM",
  AZN: "az-AZ",
  BTN: "dz-BT",
  MVR: "dv-MV",
};

// ─── Currency symbols ─────────────────────────────────────────────

export const CURRENCY_SYMBOLS: Record<string, string> = {
  INR: "\u20B9",
  USD: "$",
  EUR: "\u20AC",
  GBP: "\u00A3",
  JPY: "\u00A5",
  AUD: "A$",
  CAD: "C$",
  SGD: "S$",
  AED: "\u062F.\u0625",
  SAR: "\uFDFC",
  PKR: "\u20A8",
  BDT: "\u09F3",
  LKR: "\u20A8",
  NPR: "\u20A8",
  ZAR: "R",
  NGN: "\u20A6",
  KES: "KSh",
  CHF: "CHF",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  PLN: "z\u0142",
  CZK: "K\u010D",
  HUF: "Ft",
  RON: "lei",
  BGN: "lev",
  HRK: "kn",
  ISK: "kr",
  RUB: "\u20BD",
  UAH: "\u20B4",
  BYN: "Br",
  MDL: "L",
  RSD: "din",
  BAM: "KM",
  MKD: "den",
  ALL: "L",
  CNY: "\u00A5",
  HKD: "HK$",
  TWD: "NT$",
  KRW: "\u20A9",
  KPW: "\u20A9",
  THB: "\u0E3F",
  VND: "\u20AB",
  MYR: "RM",
  IDR: "Rp",
  PHP: "\u20B1",
  BND: "B$",
  KHR: "\u17DB",
  LAK: "\u20AD",
  MMK: "K",
  MOP: "MOP",
  AFN: "\u060B",
  IRR: "\uFDFC",
  IQD: "IQD",
  SYP: "SYP",
  LBP: "LBP",
  JOD: "JD",
  ILS: "\u20AA",
  YER: "YER",
  OMR: "OMR",
  QAR: "QR",
  KWD: "KD",
  BHD: "BD",
  TRY: "\u20BA",
  EGP: "E\u00A3",
  LYD: "LD",
  TND: "DT",
  DZD: "DA",
  MAD: "DH",
  SDG: "SDG",
  SSP: "SSP",
  ETB: "Br",
  ERN: "Nfk",
  DJF: "Fdj",
  SOS: "Sh",
  TZS: "TSh",
  UGX: "USh",
  RWF: "RF",
  BIF: "FBu",
  MZN: "MT",
  ZWL: "Z$",
  ZMW: "ZK",
  MWK: "MK",
  BWP: "P",
  NAD: "N$",
  LSL: "L",
  SZL: "L",
  AOA: "Kz",
  GHS: "\u20B5",
  XOF: "CFA",
  GNF: "FG",
  SLL: "Le",
  LRD: "L$",
  MRU: "UM",
  GMD: "D",
  CVE: "$",
  STN: "Db",
  XAF: "FCFA",
  CDF: "FC",
  KMF: "CF",
  MGA: "Ar",
  MUR: "Rs",
  SCR: "SR",
  BRL: "R$",
  ARS: "$",
  MXN: "$",
  COP: "$",
  CLP: "$",
  PEN: "S/",
  VES: "Bs",
  BOB: "Bs",
  PYG: "Gs",
  UYU: "$U",
  GYD: "G$",
  SRD: "Sr$",
  CRC: "\u20A1",
  GTQ: "Q",
  HNL: "L",
  NIO: "C$",
  CUP: "$",
  DOP: "RD$",
  HTG: "G",
  JMD: "J$",
  TTD: "TT$",
  BBD: "Bds$",
  BSD: "B$",
  XCD: "EC$",
  BZD: "BZ$",
  NZD: "NZ$",
  FJD: "FJ$",
  PGK: "K",
  SBD: "SI$",
  VUV: "Vt",
  WST: "WS$",
  TOP: "T$",
  KZT: "\u20B8",
  UZS: "so'm",
  TMT: "m",
  KGS: "som",
  TJS: "SM",
  MNT: "\u20AE",
  GEL: "\u20BE",
  AMD: "\u058F",
  AZN: "\u20BC",
  BTN: "Nu.",
  MVR: "Rf",
};

// ─── Currency names ───────────────────────────────────────────────

export const CURRENCY_NAMES: Record<string, string> = {
  INR: "Indian Rupee",
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  SGD: "Singapore Dollar",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  PKR: "Pakistani Rupee",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  NPR: "Nepalese Rupee",
  ZAR: "South African Rand",
  NGN: "Nigerian Naira",
  KES: "Kenyan Shilling",
  CHF: "Swiss Franc",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Zloty",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  BGN: "Bulgarian Lev",
  HRK: "Croatian Kuna",
  ISK: "Icelandic Krona",
  RUB: "Russian Ruble",
  UAH: "Ukrainian Hryvnia",
  BYN: "Belarusian Ruble",
  MDL: "Moldovan Leu",
  RSD: "Serbian Dinar",
  BAM: "Bosnian Mark",
  MKD: "Macedonian Denar",
  ALL: "Albanian Lek",
  CNY: "Chinese Yuan",
  HKD: "Hong Kong Dollar",
  TWD: "Taiwan Dollar",
  KRW: "South Korean Won",
  KPW: "North Korean Won",
  THB: "Thai Baht",
  VND: "Vietnamese Dong",
  MYR: "Malaysian Ringgit",
  IDR: "Indonesian Rupiah",
  PHP: "Philippine Peso",
  BND: "Brunei Dollar",
  KHR: "Cambodian Riel",
  LAK: "Lao Kip",
  MMK: "Myanmar Kyat",
  MOP: "Macanese Pataca",
  AFN: "Afghan Afghani",
  IRR: "Iranian Rial",
  IQD: "Iraqi Dinar",
  SYP: "Syrian Pound",
  LBP: "Lebanese Pound",
  JOD: "Jordanian Dinar",
  ILS: "Israeli Shekel",
  YER: "Yemeni Rial",
  OMR: "Omani Rial",
  QAR: "Qatari Riyal",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  TRY: "Turkish Lira",
  EGP: "Egyptian Pound",
  LYD: "Libyan Dinar",
  TND: "Tunisian Dinar",
  DZD: "Algerian Dinar",
  MAD: "Moroccan Dirham",
  SDG: "Sudanese Pound",
  SSP: "South Sudanese Pound",
  ETB: "Ethiopian Birr",
  ERN: "Eritrean Nakfa",
  DJF: "Djiboutian Franc",
  SOS: "Somali Shilling",
  TZS: "Tanzanian Shilling",
  UGX: "Ugandan Shilling",
  RWF: "Rwandan Franc",
  BIF: "Burundian Franc",
  MZN: "Mozambican Metical",
  ZWL: "Zimbabwean Dollar",
  ZMW: "Zambian Kwacha",
  MWK: "Malawian Kwacha",
  BWP: "Botswana Pula",
  NAD: "Namibian Dollar",
  LSL: "Lesotho Loti",
  SZL: "Swazi Lilangeni",
  AOA: "Angolan Kwanza",
  GHS: "Ghanaian Cedi",
  XOF: "West African CFA Franc",
  GNF: "Guinean Franc",
  SLL: "Sierra Leonean Leone",
  LRD: "Liberian Dollar",
  MRU: "Mauritanian Ouguiya",
  GMD: "Gambian Dalasi",
  CVE: "Cape Verdean Escudo",
  STN: "São Tomé Dobra",
  XAF: "Central African CFA Franc",
  CDF: "Congolese Franc",
  KMF: "Comorian Franc",
  MGA: "Malagasy Ariary",
  MUR: "Mauritian Rupee",
  SCR: "Seychellois Rupee",
  BRL: "Brazilian Real",
  ARS: "Argentine Peso",
  MXN: "Mexican Peso",
  COP: "Colombian Peso",
  CLP: "Chilean Peso",
  PEN: "Peruvian Sol",
  VES: "Venezuelan Bolivar",
  BOB: "Bolivian Boliviano",
  PYG: "Paraguayan Guarani",
  UYU: "Uruguayan Peso",
  GYD: "Guyanese Dollar",
  SRD: "Surinamese Dollar",
  CRC: "Costa Rican Colon",
  GTQ: "Guatemalan Quetzal",
  HNL: "Honduran Lempira",
  NIO: "Nicaraguan Cordoba",
  CUP: "Cuban Peso",
  DOP: "Dominican Peso",
  HTG: "Haitian Gourde",
  JMD: "Jamaican Dollar",
  TTD: "Trinidad Dollar",
  BBD: "Barbadian Dollar",
  BSD: "Bahamian Dollar",
  XCD: "East Caribbean Dollar",
  BZD: "Belize Dollar",
  NZD: "New Zealand Dollar",
  FJD: "Fijian Dollar",
  PGK: "Papua New Guinean Kina",
  SBD: "Solomon Islands Dollar",
  VUV: "Vanuatu Vatu",
  WST: "Samoan Tala",
  TOP: "Tongan Pa'anga",
  KZT: "Kazakhstani Tenge",
  UZS: "Uzbekistani Som",
  TMT: "Turkmenistani Manat",
  KGS: "Kyrgyzstani Som",
  TJS: "Tajikistani Somoni",
  MNT: "Mongolian Tugrik",
  GEL: "Georgian Lari",
  AMD: "Armenian Dram",
  AZN: "Azerbaijani Manat",
  BTN: "Bhutanese Ngultrum",
  MVR: "Maldivian Rufiyaa",
};

// ─── Supported currencies list (derived from the maps above) ──────

export interface CurrencyInfo {
  code: string;
  symbol: string;
  name: string;
}

export const SUPPORTED_CURRENCIES: CurrencyInfo[] = Object.keys(CURRENCY_SYMBOLS).map((code) => ({
  code,
  symbol: CURRENCY_SYMBOLS[code],
  name: CURRENCY_NAMES[code] || code,
}));

/** Set of all supported currency codes for validation */
export const SUPPORTED_CURRENCY_CODES = new Set(Object.keys(CURRENCY_SYMBOLS));

/** Check if a currency code is supported */
export function isSupportedCurrency(code: string): boolean {
  return SUPPORTED_CURRENCY_CODES.has(code);
}
